name: demo-api CI

on:
  push:
    branches: [ "dev", "feature/**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/demo_api
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Run tests
        env:
          PYTHONPATH: .
        run: pytest -q

  docker-build:             # <-- keep this name for branch protection
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'   # only push from dev
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./apps/demo_api
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/demo-api:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/demo-api:dev-latest
